[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install --include=workspace-root"]

[phases.build]
cmds = [
  "npm run build --workspace=@memodrops/shared",
  "npm run build --workspace=backend"
]

[start]
cmd = "npm run start --workspace=backend"
